//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInformation
    {
        public int ServiceID { get; set; }
        public string ServiceTitle { get; set; }
        public Nullable<double> Price { get; set; }
        public string Category { get; set; }
        public string EnglishLevel { get; set; }
        public string ResponseTime { get; set; }
        public string DeliveryTime { get; set; }
        public string Skills { get; set; }
        public string Address { get; set; }
        public string ServiceDetail { get; set; }
    }
}
